#!/usr/bin/env bash
# =============================================================================
# Provision VM via Ansible
#
# Dynamically gets the VM IP (from Multipass on macOS, or vm-ip.txt fallback),
# generates ansible/inventory.ini with ansible_user=ubuntu, then runs the
# provision-vm playbook to install Docker CE + Dagster on the VM.
#
# Usage:
#   bash scripts/provision-vm.sh               # auto-detect IP
#   VM_IP=192.168.64.5 bash scripts/provision-vm.sh  # override IP
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ANSIBLE_DIR="$REPO_ROOT/ansible"
VM_IP_FILE="$REPO_ROOT/vm-ip.txt"
INVENTORY_FILE="$ANSIBLE_DIR/inventory.ini"
SSH_KEY="$HOME/.ssh/thesis_vm"

# ---- Resolve VM IP ----
if [[ -n "${VM_IP:-}" ]]; then
  echo "-> Using VM_IP from environment: $VM_IP"
elif command -v multipass &>/dev/null && multipass info thesis-vm &>/dev/null 2>&1; then
  VM_IP="$(multipass info thesis-vm 2>/dev/null | awk '/^IPv4:/ {print $2}')"
  echo "-> Detected Multipass VM IP: $VM_IP"
  echo "$VM_IP" > "$VM_IP_FILE"
elif [[ -f "$VM_IP_FILE" ]]; then
  VM_IP="$(cat "$VM_IP_FILE" | tr -d '[:space:]')"
  echo "-> Using VM IP from $VM_IP_FILE: $VM_IP"
else
  echo "[FAIL] No VM IP found."
  echo "   Run: make bootstrap   (to create the VM)"
  echo "   Or:  VM_IP=<ip> make vm-provision"
  exit 1
fi

# ---- Ensure SSH key exists ----
# Multipass VMs use the default ubuntu user with cloud-init.
# For a new key, inject it via: multipass exec thesis-vm -- bash -c "..."
if [[ ! -f "$SSH_KEY" ]]; then
  echo "-> Generating thesis SSH key..."
  ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -C "thesis-vm"
  echo ""
  echo "[INFO] Public key generated. Inject it into the VM:"
  echo "   multipass exec thesis-vm -- bash -c \"
  echo "     \"mkdir -p ~/.ssh && echo '$(cat ${SSH_KEY}.pub)' >> ~/.ssh/authorized_keys\""
  echo ""
fi

# ---- Generate inventory ----
echo "-> Generating Ansible inventory..."
cat > "$INVENTORY_FILE" <<EOF
# Auto-generated by provision-vm.sh -- do NOT commit (see .gitignore)
[thesis_vm]
thesis-vm ansible_host=${VM_IP} ansible_user=ubuntu ansible_ssh_private_key_file=${SSH_KEY} ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[thesis_vm:vars]
ansible_python_interpreter=/usr/bin/python3
EOF
echo "[OK] Inventory written to $INVENTORY_FILE"

# ---- Verify SSH is reachable ----
echo ""
echo "-> Testing SSH connectivity to $VM_IP..."
if ! ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
    "ubuntu@$VM_IP" "echo ok" &>/dev/null; then
  echo "[FAIL] Cannot SSH to ubuntu@$VM_IP"
  echo "   Ensure the VM is running:"
  echo "     multipass start thesis-vm"
  echo "   Ensure the SSH key is authorised in the VM:"
  echo "     multipass exec thesis-vm -- bash -c \"
  echo "       \"echo '$(cat ${SSH_KEY}.pub)' >> ~/.ssh/authorized_keys\""
  exit 1
fi
echo "[OK] SSH connection OK"

# ---- Run playbook (or SSH fallback on Windows) ----
echo ""
echo "----------------------------------------------------------------"
echo "Running provisioning..."
echo "----------------------------------------------------------------"
echo ""

# Ansible doesn't run natively on Windows (no os.get_blocking).
# On Windows (Git Bash / MINGW), provision via SSH directly.
if [[ "${MSYSTEM:-}" == MINGW* ]] || [[ "${OS:-}" == "Windows_NT" ]]; then
  echo "-> Windows detected: provisioning via SSH (Ansible not supported on Windows)"
  ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no "ubuntu@$VM_IP" bash -s << 'SSHSCRIPT'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
echo "[1/6] Updating apt..."
sudo apt-get update -qq
echo "[2/6] Installing prerequisites..."
sudo apt-get install -y -qq ca-certificates curl gnupg lsb-release netcat-openbsd git
echo "[3/6] Adding Docker GPG key..."
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
echo "[4/6] Adding Docker repo..."
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
echo "[5/6] Installing Docker CE..."
sudo apt-get update -qq
sudo apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
echo "[6/6] Configuring Docker..."
sudo systemctl enable docker && sudo systemctl start docker
sudo usermod -aG docker ubuntu
echo "[OK] Docker $(docker --version)"
SSHSCRIPT
else
  # Run from ansible directory so ansible.cfg is picked up
  (cd "$ANSIBLE_DIR" && ansible-playbook \
    -i "inventory.ini" \
    "playbooks/provision-vm.yml" \
    -v)
fi

echo ""
echo "================================================================"
echo "[OK] VM Provisioning Complete"
echo "================================================================"
echo ""
echo "  Docker CE installed on VM."
echo "  Next: make build && make push && make deploy"
echo ""
