#!/usr/bin/env bash
# =============================================================================
# Provision VM via Ansible
#
# Generates the Ansible inventory from vm-ip.txt (created by bootstrap/create-vm),
# then runs the provision-vm playbook.
#
# Usage:
#   bash scripts/provision-vm.sh               # uses vm-ip.txt
#   VM_IP=192.168.64.5 bash scripts/provision-vm.sh  # override IP
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ANSIBLE_DIR="$REPO_ROOT/ansible"
VM_IP_FILE="$REPO_ROOT/vm-ip.txt"
INVENTORY_FILE="$ANSIBLE_DIR/inventory.ini"
SSH_KEY="$HOME/.ssh/thesis_vm"

# ---- Resolve VM IP ----
if [[ -n "${VM_IP:-}" ]]; then
  echo "→ Using VM_IP from environment: $VM_IP"
elif [[ -f "$VM_IP_FILE" ]]; then
  VM_IP="$(cat "$VM_IP_FILE" | tr -d '[:space:]')"
  echo "→ Using VM IP from $VM_IP_FILE: $VM_IP"
else
  echo "[FAIL] No VM IP found."
  echo "   Run: make bootstrap   (to create the VM)"
  echo "   Or:  VM_IP=<ip> make vm-provision"
  exit 1
fi

# ---- Generate inventory ----
echo "→ Generating Ansible inventory..."
cat > "$INVENTORY_FILE" <<EOF
# Auto-generated by provision-vm.sh — do NOT commit (see .gitignore)
[thesis_vm]
thesis-vm ansible_host=${VM_IP} ansible_user=ubuntu ansible_ssh_private_key_file=${SSH_KEY} ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[thesis_vm:vars]
ansible_python_interpreter=/usr/bin/python3
EOF
echo "[OK] Inventory written to $INVENTORY_FILE"

# ---- Verify SSH is reachable ----
echo ""
echo "→ Testing SSH connectivity to $VM_IP..."
if ! ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
    "ubuntu@$VM_IP" "echo ok" &>/dev/null; then
  echo "[FAIL] Cannot SSH to ubuntu@$VM_IP"
  echo "   Ensure the VM is running and accessible."
  echo "   Expected SSH key: $SSH_KEY"
  exit 1
fi
echo "[OK] SSH connection OK"

# ---- Install Ansible collections (once) ----
echo ""
echo "→ Installing Ansible Galaxy requirements..."
ansible-galaxy collection install community.postgresql --timeout 60 2>/dev/null && echo "[OK] community.postgresql ready" || echo "[WARN]  ansible-galaxy install skipped (may already be present)"

# ---- Run playbook ----
echo ""
echo "----------------------------------------------------------------"
echo "Running Ansible provisioning playbook..."
echo "----------------------------------------------------------------"
echo ""

ansible-playbook \
  -i "$INVENTORY_FILE" \
  "$ANSIBLE_DIR/playbooks/provision-vm.yml" \
  --extra-vars "dagster_version=1.12.7 postgres_password=dagster workload_duration=30" \
  -v

echo ""
echo "================================================================"
echo "[OK] VM Provisioning Complete"
echo "================================================================"
echo ""
echo "  VM:       $VM_IP"
echo "  SSH:      ssh -i $SSH_KEY ubuntu@$VM_IP"
echo "  gRPC:     nc -zv $VM_IP 4000"
echo "  Next:     make exp1-vm"
echo ""
