[project]
name = "src"
version = "0.1.0"
description = "Dagster workload for thesis VM vs K8s benchmarking"
requires-python = ">=3.13"
dependencies = [
    "dagster==1.12.22",
    "dagster-postgres==0.28.22",
    "dagster-webserver==1.12.22",
    "dagster-docker==0.28.22",
    "dagster-k8s==0.28.22",
    "pandas>=3.0.2",
    "matplotlib>=3.10.8",
    "scipy>=1.17.1",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "nbconvert>=7.17.1",
    "numpy>=2.4.4",
    "psutil>=7.2.2",
]

[build-system]
requires = ["setuptools>=71"]
build-backend = "setuptools.build_meta"
